language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ./node_modules
services:
  - "mongodb"
install:
  - npm install
before_script:
  - "cp .env.example .env"
script:
  - "yarn run test:e2e"
branches:
  only:
    - master
